### ISSUE TITLE
Error in CMAKE

### ISSUE THREAD

**Issue by baolamhuynh** [rohan-shah/mpMapInteractive#1]
We downloaded your Rcpp-windows and built it.  That seems to be ok.  We have C:\Rcpp-windows\build\Debug\Rcpp.lib

We then moved on to build mpMapInteractive.  We get the following error:

![image](https://user-images.githubusercontent.com/32344791/30940159-f1b72c18-a394-11e7-8338-b097a7a2d2c1.png)

CMake Error at CMakeLists.txt:8 (find_package):
  By not providing "FindRcpp.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Rcpp", but
  CMake did not find one.

  Could not find a package configuration file provided by "Rcpp" with any of
  the following names:

    RcppConfig.cmake
    rcpp-config.cmake

  Add the installation prefix of "Rcpp" to CMAKE_PREFIX_PATH or set
  "Rcpp_DIR" to a directory containing one of the above files.  If "Rcpp"
  provides a separate development package or SDK, be sure it has been
  installed.

**Comment by rohan-shah** [comment]
So, a couple of things:

1. The instructions you're trying to follow aren't very well written. I'm sorry. 
2.  You need to set Rcpp_DIR (the line highlighted in red) to **C:\Rcpp-windows\build**, point number 2 on the list of instructions.
3. This package is no longer actively maintained / supported. An updated version is available under repository mpMapInteractive**2**, and this package **is supported**. You can download a binary version of **that package** under the releases section.
4. I have uploaded a binary version for **this package** under the releases section, compiled under VS 2015. 

I really don't recommend using this package.......
