### ISSUE TITLE
internal.h header not found

### ISSUE THREAD

**Issue by eylenth** [rohan-shah/mpMapInteractive#2]
Hi 

When compiling the package, I'm receiving the following error:

```bash
mpMapInteractive/src/register.cpp:5:10: fatal error: internal.h: No such file or directory
--
#include <internal.h>^M

```
Where can this internal.h header be found ?

I know this package is really old, but one of our users wants to use this package.

**Comment by rohan-shah** [comment]
There is no longer any support provided for this package. A *much* improved version is available under repository mpMapInteractive2. Binary versions of that package are available for windows.

If you want to compile that package yourself, the build instructions are complicated but I am willing to support it, and make improvements to the build process if required.

**Comment by eylenth** [comment]
Well, I'm getting the same error message
I have reported the same issue in mpMapInteractive2
